# Generated by Django 3.1.2 on 2020-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201021_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/profile/img', verbose_name='Аватарка профиля'),
        ),
    ]
